version: "3"

services:
    nm-self-learn-db:
        image: postgres:14
        environment:
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: SelfLearningDb
            PGDATA: /var/lib/postgresql/data
        networks:
            - nm-self-learn
        volumes:
            - ./data/postgres_data:/var/lib/postgresql/data

    minio:
        image: minio/minio
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000" # public port
            - "9001:9001" # admin port
        environment:
            MINIO_ROOT_USER: minioadmin
            MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
        networks:
            - nm-self-learn
        volumes:
            - ./data/minio/data:/data
            - ./data/minio/config:/root/.minio

    piston:
        image: ghcr.io/e-learning-by-sse/infrastructure-piston:latest
        restart: always
        networks:
            - nm-self-learn
        volumes:
            - ./data/piston:/piston
        tmpfs:
            - /piston/jobs:exec
            - /tmp:exec

    nm-self-learning:
        image: ghcr.io/e-learning-by-sse/nm-self-learning:latest
        restart: unless-stopped
        ports:
            - 3000:3000
        depends_on:
            - "nm-self-learn-db"
            - "minio"
            - "piston"
        networks:
            - nm-self-learn
        volumes:
            - ./data/selflearn/state:/app/state
            - ./data/selflearn/dist:/app/dist
        environment:
            - DB_HOST=nm-self-learn-db
            - DB_PORT=5432
            - NEXT_PUBLIC_IS_DEMO_INSTANCE=false
            - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@nm-self-learn-db:5432/SelfLearningDb
            - NEXT_ASSET_PREFIX=${ASSET_PREFIX}
            - NEXT_PUBLIC_BASE_PATH=${ASSET_PREFIX}
            - MINIO_BUCKET_NAME=upload
            - MINIO_ENDPOINT=minio
            - MINIO_PORT=9010
            - MINIO_USE_SSL=false
            - MINIO_ACCESS_KEY=${MINIO_ACCESS_KEY}
            - MINIO_SECRET_KEY=${MINIO_SECRET_KEY}
            - NEXTAUTH_URL=${NEXTAUTH_REDIRECT_URL}
            - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
            - PISTON_URL=http://piston:2000
            - KEYCLOAK_ISSUER_URL=${KEYCLOAK_ISSUER_URL}
            - KEYCLOAK_CLIENT_ID=${KEYCLOAK_CLIENT_ID}
            - KEYCLOAK_CLIENT_SECRET=${KEYCLOAK_CLIENT_SECRET}
networks:
    nm-self-learn:
