# Use the docker/dev-environments-javascript:stable-1 image as the base image
FROM docker/dev-environments-javascript:stable-1

# Install the nx build tool
RUN npm install -g nx

# Expose port 4200 for the application to listen on
EXPOSE 4200

USER node
