import { I18N_NAMESPACE as NS_AI_TUTOR } from "@self-learning/ai-tutor";
export * from "./lib/author/edit-author-dialog";
export * from "./lib/course/course-editor";
export * from "./lib/lesson/lesson-editor";
export * from "./lib/lesson/lesson-form-model";
export * from "./lib/course/course-form-model";
export * from "./lib/subject/subject-editor";
export * from "./lib/subject/permissions-dialog";
export * from "./lib/lesson/forms/license-form";
export * from "./lib/skills/repository/repository-overview";
export * from "./lib/skills/folder-editor";
export * from "./lib/course/full-course-export";
export * from "./lib/course/course-export/course-export-dialog";
export * from "./lib/group/group-editor";
export * from "./lib/group/forms/members-form";
export * from "./lib/group/editors/group-info";
export * from "./lib/group/editors/group-members";
export * from "./lib/group/editors/group-permission";
export * from "./lib/group/editors/group-picker";
export * from "./lib/group/dialogs/search-group-dialog";
export * from "./lib/group/dialogs/merge-groups-dialog";
export * from "./lib/group/dialogs/promote-to-author";
export * from "./lib/group/dialogs/related-permissions-dialog";
export * from "./lib/group/misc/delete-option";
export * from "./lib/group/misc/leave-option";
export const I18N_NAMESPACE = Array.from(new Set(["common", "feature-teaching", ...NS_AI_TUTOR]));
